/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// Status1c5EnumUndergoingAuthentication struct for Status1c5EnumUndergoingAuthentication
type Status1c5EnumUndergoingAuthentication struct {
	Short string `json:"short"`
	Long string `json:"long"`
	Description string `json:"description"`
}

// NewStatus1c5EnumUndergoingAuthentication instantiates a new Status1c5EnumUndergoingAuthentication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatus1c5EnumUndergoingAuthentication(short string, long string, description string) *Status1c5EnumUndergoingAuthentication {
	this := Status1c5EnumUndergoingAuthentication{}
	this.Short = short
	this.Long = long
	this.Description = description
	return &this
}

// NewStatus1c5EnumUndergoingAuthenticationWithDefaults instantiates a new Status1c5EnumUndergoingAuthentication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatus1c5EnumUndergoingAuthenticationWithDefaults() *Status1c5EnumUndergoingAuthentication {
	this := Status1c5EnumUndergoingAuthentication{}
	return &this
}

// GetShort returns the Short field value
func (o *Status1c5EnumUndergoingAuthentication) GetShort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Short
}

// GetShortOk returns a tuple with the Short field value
// and a boolean to check if the value has been set.
func (o *Status1c5EnumUndergoingAuthentication) GetShortOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Short, true
}

// SetShort sets field value
func (o *Status1c5EnumUndergoingAuthentication) SetShort(v string) {
	o.Short = v
}

// GetLong returns the Long field value
func (o *Status1c5EnumUndergoingAuthentication) GetLong() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Long
}

// GetLongOk returns a tuple with the Long field value
// and a boolean to check if the value has been set.
func (o *Status1c5EnumUndergoingAuthentication) GetLongOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Long, true
}

// SetLong sets field value
func (o *Status1c5EnumUndergoingAuthentication) SetLong(v string) {
	o.Long = v
}

// GetDescription returns the Description field value
func (o *Status1c5EnumUndergoingAuthentication) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Status1c5EnumUndergoingAuthentication) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Status1c5EnumUndergoingAuthentication) SetDescription(v string) {
	o.Description = v
}

func (o Status1c5EnumUndergoingAuthentication) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["short"] = o.Short
	}
	if true {
		toSerialize["long"] = o.Long
	}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableStatus1c5EnumUndergoingAuthentication struct {
	value *Status1c5EnumUndergoingAuthentication
	isSet bool
}

func (v NullableStatus1c5EnumUndergoingAuthentication) Get() *Status1c5EnumUndergoingAuthentication {
	return v.value
}

func (v *NullableStatus1c5EnumUndergoingAuthentication) Set(val *Status1c5EnumUndergoingAuthentication) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumUndergoingAuthentication) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumUndergoingAuthentication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumUndergoingAuthentication(val *Status1c5EnumUndergoingAuthentication) *NullableStatus1c5EnumUndergoingAuthentication {
	return &NullableStatus1c5EnumUndergoingAuthentication{value: val, isSet: true}
}

func (v NullableStatus1c5EnumUndergoingAuthentication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumUndergoingAuthentication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


