/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"fmt"
)

// Status1c5EnumLinked the model 'Status1c5EnumLinked'
type Status1c5EnumLinked string

// List of Status1c5EnumLinked
const (
	STATUS1C5ENUMLINKED_LN Status1c5EnumLinked = "LN"
	STATUS1C5ENUMLINKED_LINKED Status1c5EnumLinked = "LINKED"
)

// All allowed values of Status1c5EnumLinked enum
var AllowedStatus1c5EnumLinkedEnumValues = []Status1c5EnumLinked{
	"LN",
	"LINKED",
}

func (v *Status1c5EnumLinked) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status1c5EnumLinked(value)
	for _, existing := range AllowedStatus1c5EnumLinkedEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status1c5EnumLinked", value)
}

// NewStatus1c5EnumLinkedFromValue returns a pointer to a valid Status1c5EnumLinked
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus1c5EnumLinkedFromValue(v string) (*Status1c5EnumLinked, error) {
	ev := Status1c5EnumLinked(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status1c5EnumLinked: valid values are %v", v, AllowedStatus1c5EnumLinkedEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status1c5EnumLinked) IsValid() bool {
	for _, existing := range AllowedStatus1c5EnumLinkedEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status1c5EnumLinked value
func (v Status1c5EnumLinked) Ptr() *Status1c5EnumLinked {
	return &v
}

type NullableStatus1c5EnumLinked struct {
	value *Status1c5EnumLinked
	isSet bool
}

func (v NullableStatus1c5EnumLinked) Get() *Status1c5EnumLinked {
	return v.value
}

func (v *NullableStatus1c5EnumLinked) Set(val *Status1c5EnumLinked) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumLinked) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumLinked) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumLinked(val *Status1c5EnumLinked) *NullableStatus1c5EnumLinked {
	return &NullableStatus1c5EnumLinked{value: val, isSet: true}
}

func (v NullableStatus1c5EnumLinked) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumLinked) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

