/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// AccountV2StatusEnumError struct for AccountV2StatusEnumError
type AccountV2StatusEnumError struct {
	ERROR string `json:"ERROR"`
}

// NewAccountV2StatusEnumError instantiates a new AccountV2StatusEnumError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountV2StatusEnumError(eRROR string) *AccountV2StatusEnumError {
	this := AccountV2StatusEnumError{}
	this.ERROR = eRROR
	return &this
}

// NewAccountV2StatusEnumErrorWithDefaults instantiates a new AccountV2StatusEnumError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountV2StatusEnumErrorWithDefaults() *AccountV2StatusEnumError {
	this := AccountV2StatusEnumError{}
	return &this
}

// GetERROR returns the ERROR field value
func (o *AccountV2StatusEnumError) GetERROR() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ERROR
}

// GetERROROk returns a tuple with the ERROR field value
// and a boolean to check if the value has been set.
func (o *AccountV2StatusEnumError) GetERROROk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ERROR, true
}

// SetERROR sets field value
func (o *AccountV2StatusEnumError) SetERROR(v string) {
	o.ERROR = v
}

func (o AccountV2StatusEnumError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ERROR"] = o.ERROR
	}
	return json.Marshal(toSerialize)
}

type NullableAccountV2StatusEnumError struct {
	value *AccountV2StatusEnumError
	isSet bool
}

func (v NullableAccountV2StatusEnumError) Get() *AccountV2StatusEnumError {
	return v.value
}

func (v *NullableAccountV2StatusEnumError) Set(val *AccountV2StatusEnumError) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountV2StatusEnumError) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountV2StatusEnumError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountV2StatusEnumError(val *AccountV2StatusEnumError) *NullableAccountV2StatusEnumError {
	return &NullableAccountV2StatusEnumError{value: val, isSet: true}
}

func (v NullableAccountV2StatusEnumError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountV2StatusEnumError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


