/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"fmt"
)

// Status1c5EnumGivingConsent the model 'Status1c5EnumGivingConsent'
type Status1c5EnumGivingConsent string

// List of Status1c5EnumGivingConsent
const (
	STATUS1C5ENUMGIVINGCONSENT_GC Status1c5EnumGivingConsent = "GC"
	STATUS1C5ENUMGIVINGCONSENT_GIVING_CONSENT Status1c5EnumGivingConsent = "GIVING_CONSENT"
)

// All allowed values of Status1c5EnumGivingConsent enum
var AllowedStatus1c5EnumGivingConsentEnumValues = []Status1c5EnumGivingConsent{
	"GC",
	"GIVING_CONSENT",
}

func (v *Status1c5EnumGivingConsent) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status1c5EnumGivingConsent(value)
	for _, existing := range AllowedStatus1c5EnumGivingConsentEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status1c5EnumGivingConsent", value)
}

// NewStatus1c5EnumGivingConsentFromValue returns a pointer to a valid Status1c5EnumGivingConsent
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus1c5EnumGivingConsentFromValue(v string) (*Status1c5EnumGivingConsent, error) {
	ev := Status1c5EnumGivingConsent(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status1c5EnumGivingConsent: valid values are %v", v, AllowedStatus1c5EnumGivingConsentEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status1c5EnumGivingConsent) IsValid() bool {
	for _, existing := range AllowedStatus1c5EnumGivingConsentEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status1c5EnumGivingConsent value
func (v Status1c5EnumGivingConsent) Ptr() *Status1c5EnumGivingConsent {
	return &v
}

type NullableStatus1c5EnumGivingConsent struct {
	value *Status1c5EnumGivingConsent
	isSet bool
}

func (v NullableStatus1c5EnumGivingConsent) Get() *Status1c5EnumGivingConsent {
	return v.value
}

func (v *NullableStatus1c5EnumGivingConsent) Set(val *Status1c5EnumGivingConsent) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumGivingConsent) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumGivingConsent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumGivingConsent(val *Status1c5EnumGivingConsent) *NullableStatus1c5EnumGivingConsent {
	return &NullableStatus1c5EnumGivingConsent{value: val, isSet: true}
}

func (v NullableStatus1c5EnumGivingConsent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumGivingConsent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

