/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"time"
)

// AccountTransaction struct for AccountTransaction
type AccountTransaction struct {
	TransactionId *string `json:"transactionId,omitempty"`
	EntryReference *string `json:"entryReference,omitempty"`
	CheckId *string `json:"checkId,omitempty"`
	CreditorId *string `json:"creditorId,omitempty"`
	CreditorName *string `json:"creditorName,omitempty"`
	CreditorAccount *AccountTransactionCreditorAccount `json:"creditorAccount,omitempty"`
	DebtorName *string `json:"debtorName,omitempty"`
	DebtorAccount *AccountTransactionDebtorAccount `json:"debtorAccount,omitempty"`
	TransactionAmount *AccountTransactionTransactionAmount `json:"transactionAmount,omitempty"`
	BankTransactionCode *string `json:"bankTransactionCode,omitempty"`
	BookingDate *time.Time `json:"bookingDate,omitempty"`
	ValueDate *time.Time `json:"valueDate,omitempty"`
	MandateId *string `json:"mandateId,omitempty"`
	PurposeCode *string `json:"purposeCode,omitempty"`
	RemittanceInformationUnstructured *string `json:"remittanceInformationUnstructured,omitempty"`
	AdditionalInformation *string `json:"additionalInformation,omitempty"`
	ProprietaryBankTransactionCode *string `json:"proprietaryBankTransactionCode,omitempty"`
	UltimateCreditor *string `json:"ultimateCreditor,omitempty"`
	UltimateDebtor *string `json:"ultimateDebtor,omitempty"`
}

// NewAccountTransaction instantiates a new AccountTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountTransaction() *AccountTransaction {
	this := AccountTransaction{}
	return &this
}

// NewAccountTransactionWithDefaults instantiates a new AccountTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountTransactionWithDefaults() *AccountTransaction {
	this := AccountTransaction{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *AccountTransaction) GetTransactionId() string {
	if o == nil || o.TransactionId == nil {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetTransactionIdOk() (*string, bool) {
	if o == nil || o.TransactionId == nil {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *AccountTransaction) HasTransactionId() bool {
	if o != nil && o.TransactionId != nil {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *AccountTransaction) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetEntryReference returns the EntryReference field value if set, zero value otherwise.
func (o *AccountTransaction) GetEntryReference() string {
	if o == nil || o.EntryReference == nil {
		var ret string
		return ret
	}
	return *o.EntryReference
}

// GetEntryReferenceOk returns a tuple with the EntryReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetEntryReferenceOk() (*string, bool) {
	if o == nil || o.EntryReference == nil {
		return nil, false
	}
	return o.EntryReference, true
}

// HasEntryReference returns a boolean if a field has been set.
func (o *AccountTransaction) HasEntryReference() bool {
	if o != nil && o.EntryReference != nil {
		return true
	}

	return false
}

// SetEntryReference gets a reference to the given string and assigns it to the EntryReference field.
func (o *AccountTransaction) SetEntryReference(v string) {
	o.EntryReference = &v
}

// GetCheckId returns the CheckId field value if set, zero value otherwise.
func (o *AccountTransaction) GetCheckId() string {
	if o == nil || o.CheckId == nil {
		var ret string
		return ret
	}
	return *o.CheckId
}

// GetCheckIdOk returns a tuple with the CheckId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetCheckIdOk() (*string, bool) {
	if o == nil || o.CheckId == nil {
		return nil, false
	}
	return o.CheckId, true
}

// HasCheckId returns a boolean if a field has been set.
func (o *AccountTransaction) HasCheckId() bool {
	if o != nil && o.CheckId != nil {
		return true
	}

	return false
}

// SetCheckId gets a reference to the given string and assigns it to the CheckId field.
func (o *AccountTransaction) SetCheckId(v string) {
	o.CheckId = &v
}

// GetCreditorId returns the CreditorId field value if set, zero value otherwise.
func (o *AccountTransaction) GetCreditorId() string {
	if o == nil || o.CreditorId == nil {
		var ret string
		return ret
	}
	return *o.CreditorId
}

// GetCreditorIdOk returns a tuple with the CreditorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetCreditorIdOk() (*string, bool) {
	if o == nil || o.CreditorId == nil {
		return nil, false
	}
	return o.CreditorId, true
}

// HasCreditorId returns a boolean if a field has been set.
func (o *AccountTransaction) HasCreditorId() bool {
	if o != nil && o.CreditorId != nil {
		return true
	}

	return false
}

// SetCreditorId gets a reference to the given string and assigns it to the CreditorId field.
func (o *AccountTransaction) SetCreditorId(v string) {
	o.CreditorId = &v
}

// GetCreditorName returns the CreditorName field value if set, zero value otherwise.
func (o *AccountTransaction) GetCreditorName() string {
	if o == nil || o.CreditorName == nil {
		var ret string
		return ret
	}
	return *o.CreditorName
}

// GetCreditorNameOk returns a tuple with the CreditorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetCreditorNameOk() (*string, bool) {
	if o == nil || o.CreditorName == nil {
		return nil, false
	}
	return o.CreditorName, true
}

// HasCreditorName returns a boolean if a field has been set.
func (o *AccountTransaction) HasCreditorName() bool {
	if o != nil && o.CreditorName != nil {
		return true
	}

	return false
}

// SetCreditorName gets a reference to the given string and assigns it to the CreditorName field.
func (o *AccountTransaction) SetCreditorName(v string) {
	o.CreditorName = &v
}

// GetCreditorAccount returns the CreditorAccount field value if set, zero value otherwise.
func (o *AccountTransaction) GetCreditorAccount() AccountTransactionCreditorAccount {
	if o == nil || o.CreditorAccount == nil {
		var ret AccountTransactionCreditorAccount
		return ret
	}
	return *o.CreditorAccount
}

// GetCreditorAccountOk returns a tuple with the CreditorAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetCreditorAccountOk() (*AccountTransactionCreditorAccount, bool) {
	if o == nil || o.CreditorAccount == nil {
		return nil, false
	}
	return o.CreditorAccount, true
}

// HasCreditorAccount returns a boolean if a field has been set.
func (o *AccountTransaction) HasCreditorAccount() bool {
	if o != nil && o.CreditorAccount != nil {
		return true
	}

	return false
}

// SetCreditorAccount gets a reference to the given AccountTransactionCreditorAccount and assigns it to the CreditorAccount field.
func (o *AccountTransaction) SetCreditorAccount(v AccountTransactionCreditorAccount) {
	o.CreditorAccount = &v
}

// GetDebtorName returns the DebtorName field value if set, zero value otherwise.
func (o *AccountTransaction) GetDebtorName() string {
	if o == nil || o.DebtorName == nil {
		var ret string
		return ret
	}
	return *o.DebtorName
}

// GetDebtorNameOk returns a tuple with the DebtorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetDebtorNameOk() (*string, bool) {
	if o == nil || o.DebtorName == nil {
		return nil, false
	}
	return o.DebtorName, true
}

// HasDebtorName returns a boolean if a field has been set.
func (o *AccountTransaction) HasDebtorName() bool {
	if o != nil && o.DebtorName != nil {
		return true
	}

	return false
}

// SetDebtorName gets a reference to the given string and assigns it to the DebtorName field.
func (o *AccountTransaction) SetDebtorName(v string) {
	o.DebtorName = &v
}

// GetDebtorAccount returns the DebtorAccount field value if set, zero value otherwise.
func (o *AccountTransaction) GetDebtorAccount() AccountTransactionDebtorAccount {
	if o == nil || o.DebtorAccount == nil {
		var ret AccountTransactionDebtorAccount
		return ret
	}
	return *o.DebtorAccount
}

// GetDebtorAccountOk returns a tuple with the DebtorAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetDebtorAccountOk() (*AccountTransactionDebtorAccount, bool) {
	if o == nil || o.DebtorAccount == nil {
		return nil, false
	}
	return o.DebtorAccount, true
}

// HasDebtorAccount returns a boolean if a field has been set.
func (o *AccountTransaction) HasDebtorAccount() bool {
	if o != nil && o.DebtorAccount != nil {
		return true
	}

	return false
}

// SetDebtorAccount gets a reference to the given AccountTransactionDebtorAccount and assigns it to the DebtorAccount field.
func (o *AccountTransaction) SetDebtorAccount(v AccountTransactionDebtorAccount) {
	o.DebtorAccount = &v
}

// GetTransactionAmount returns the TransactionAmount field value if set, zero value otherwise.
func (o *AccountTransaction) GetTransactionAmount() AccountTransactionTransactionAmount {
	if o == nil || o.TransactionAmount == nil {
		var ret AccountTransactionTransactionAmount
		return ret
	}
	return *o.TransactionAmount
}

// GetTransactionAmountOk returns a tuple with the TransactionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetTransactionAmountOk() (*AccountTransactionTransactionAmount, bool) {
	if o == nil || o.TransactionAmount == nil {
		return nil, false
	}
	return o.TransactionAmount, true
}

// HasTransactionAmount returns a boolean if a field has been set.
func (o *AccountTransaction) HasTransactionAmount() bool {
	if o != nil && o.TransactionAmount != nil {
		return true
	}

	return false
}

// SetTransactionAmount gets a reference to the given AccountTransactionTransactionAmount and assigns it to the TransactionAmount field.
func (o *AccountTransaction) SetTransactionAmount(v AccountTransactionTransactionAmount) {
	o.TransactionAmount = &v
}

// GetBankTransactionCode returns the BankTransactionCode field value if set, zero value otherwise.
func (o *AccountTransaction) GetBankTransactionCode() string {
	if o == nil || o.BankTransactionCode == nil {
		var ret string
		return ret
	}
	return *o.BankTransactionCode
}

// GetBankTransactionCodeOk returns a tuple with the BankTransactionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetBankTransactionCodeOk() (*string, bool) {
	if o == nil || o.BankTransactionCode == nil {
		return nil, false
	}
	return o.BankTransactionCode, true
}

// HasBankTransactionCode returns a boolean if a field has been set.
func (o *AccountTransaction) HasBankTransactionCode() bool {
	if o != nil && o.BankTransactionCode != nil {
		return true
	}

	return false
}

// SetBankTransactionCode gets a reference to the given string and assigns it to the BankTransactionCode field.
func (o *AccountTransaction) SetBankTransactionCode(v string) {
	o.BankTransactionCode = &v
}

// GetBookingDate returns the BookingDate field value if set, zero value otherwise.
func (o *AccountTransaction) GetBookingDate() time.Time {
	if o == nil || o.BookingDate == nil {
		var ret time.Time
		return ret
	}
	return *o.BookingDate
}

// GetBookingDateOk returns a tuple with the BookingDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetBookingDateOk() (*time.Time, bool) {
	if o == nil || o.BookingDate == nil {
		return nil, false
	}
	return o.BookingDate, true
}

// HasBookingDate returns a boolean if a field has been set.
func (o *AccountTransaction) HasBookingDate() bool {
	if o != nil && o.BookingDate != nil {
		return true
	}

	return false
}

// SetBookingDate gets a reference to the given time.Time and assigns it to the BookingDate field.
func (o *AccountTransaction) SetBookingDate(v time.Time) {
	o.BookingDate = &v
}

// GetValueDate returns the ValueDate field value if set, zero value otherwise.
func (o *AccountTransaction) GetValueDate() time.Time {
	if o == nil || o.ValueDate == nil {
		var ret time.Time
		return ret
	}
	return *o.ValueDate
}

// GetValueDateOk returns a tuple with the ValueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetValueDateOk() (*time.Time, bool) {
	if o == nil || o.ValueDate == nil {
		return nil, false
	}
	return o.ValueDate, true
}

// HasValueDate returns a boolean if a field has been set.
func (o *AccountTransaction) HasValueDate() bool {
	if o != nil && o.ValueDate != nil {
		return true
	}

	return false
}

// SetValueDate gets a reference to the given time.Time and assigns it to the ValueDate field.
func (o *AccountTransaction) SetValueDate(v time.Time) {
	o.ValueDate = &v
}

// GetMandateId returns the MandateId field value if set, zero value otherwise.
func (o *AccountTransaction) GetMandateId() string {
	if o == nil || o.MandateId == nil {
		var ret string
		return ret
	}
	return *o.MandateId
}

// GetMandateIdOk returns a tuple with the MandateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetMandateIdOk() (*string, bool) {
	if o == nil || o.MandateId == nil {
		return nil, false
	}
	return o.MandateId, true
}

// HasMandateId returns a boolean if a field has been set.
func (o *AccountTransaction) HasMandateId() bool {
	if o != nil && o.MandateId != nil {
		return true
	}

	return false
}

// SetMandateId gets a reference to the given string and assigns it to the MandateId field.
func (o *AccountTransaction) SetMandateId(v string) {
	o.MandateId = &v
}

// GetPurposeCode returns the PurposeCode field value if set, zero value otherwise.
func (o *AccountTransaction) GetPurposeCode() string {
	if o == nil || o.PurposeCode == nil {
		var ret string
		return ret
	}
	return *o.PurposeCode
}

// GetPurposeCodeOk returns a tuple with the PurposeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetPurposeCodeOk() (*string, bool) {
	if o == nil || o.PurposeCode == nil {
		return nil, false
	}
	return o.PurposeCode, true
}

// HasPurposeCode returns a boolean if a field has been set.
func (o *AccountTransaction) HasPurposeCode() bool {
	if o != nil && o.PurposeCode != nil {
		return true
	}

	return false
}

// SetPurposeCode gets a reference to the given string and assigns it to the PurposeCode field.
func (o *AccountTransaction) SetPurposeCode(v string) {
	o.PurposeCode = &v
}

// GetRemittanceInformationUnstructured returns the RemittanceInformationUnstructured field value if set, zero value otherwise.
func (o *AccountTransaction) GetRemittanceInformationUnstructured() string {
	if o == nil || o.RemittanceInformationUnstructured == nil {
		var ret string
		return ret
	}
	return *o.RemittanceInformationUnstructured
}

// GetRemittanceInformationUnstructuredOk returns a tuple with the RemittanceInformationUnstructured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetRemittanceInformationUnstructuredOk() (*string, bool) {
	if o == nil || o.RemittanceInformationUnstructured == nil {
		return nil, false
	}
	return o.RemittanceInformationUnstructured, true
}

// HasRemittanceInformationUnstructured returns a boolean if a field has been set.
func (o *AccountTransaction) HasRemittanceInformationUnstructured() bool {
	if o != nil && o.RemittanceInformationUnstructured != nil {
		return true
	}

	return false
}

// SetRemittanceInformationUnstructured gets a reference to the given string and assigns it to the RemittanceInformationUnstructured field.
func (o *AccountTransaction) SetRemittanceInformationUnstructured(v string) {
	o.RemittanceInformationUnstructured = &v
}

// GetAdditionalInformation returns the AdditionalInformation field value if set, zero value otherwise.
func (o *AccountTransaction) GetAdditionalInformation() string {
	if o == nil || o.AdditionalInformation == nil {
		var ret string
		return ret
	}
	return *o.AdditionalInformation
}

// GetAdditionalInformationOk returns a tuple with the AdditionalInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetAdditionalInformationOk() (*string, bool) {
	if o == nil || o.AdditionalInformation == nil {
		return nil, false
	}
	return o.AdditionalInformation, true
}

// HasAdditionalInformation returns a boolean if a field has been set.
func (o *AccountTransaction) HasAdditionalInformation() bool {
	if o != nil && o.AdditionalInformation != nil {
		return true
	}

	return false
}

// SetAdditionalInformation gets a reference to the given string and assigns it to the AdditionalInformation field.
func (o *AccountTransaction) SetAdditionalInformation(v string) {
	o.AdditionalInformation = &v
}

// GetProprietaryBankTransactionCode returns the ProprietaryBankTransactionCode field value if set, zero value otherwise.
func (o *AccountTransaction) GetProprietaryBankTransactionCode() string {
	if o == nil || o.ProprietaryBankTransactionCode == nil {
		var ret string
		return ret
	}
	return *o.ProprietaryBankTransactionCode
}

// GetProprietaryBankTransactionCodeOk returns a tuple with the ProprietaryBankTransactionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetProprietaryBankTransactionCodeOk() (*string, bool) {
	if o == nil || o.ProprietaryBankTransactionCode == nil {
		return nil, false
	}
	return o.ProprietaryBankTransactionCode, true
}

// HasProprietaryBankTransactionCode returns a boolean if a field has been set.
func (o *AccountTransaction) HasProprietaryBankTransactionCode() bool {
	if o != nil && o.ProprietaryBankTransactionCode != nil {
		return true
	}

	return false
}

// SetProprietaryBankTransactionCode gets a reference to the given string and assigns it to the ProprietaryBankTransactionCode field.
func (o *AccountTransaction) SetProprietaryBankTransactionCode(v string) {
	o.ProprietaryBankTransactionCode = &v
}

// GetUltimateCreditor returns the UltimateCreditor field value if set, zero value otherwise.
func (o *AccountTransaction) GetUltimateCreditor() string {
	if o == nil || o.UltimateCreditor == nil {
		var ret string
		return ret
	}
	return *o.UltimateCreditor
}

// GetUltimateCreditorOk returns a tuple with the UltimateCreditor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetUltimateCreditorOk() (*string, bool) {
	if o == nil || o.UltimateCreditor == nil {
		return nil, false
	}
	return o.UltimateCreditor, true
}

// HasUltimateCreditor returns a boolean if a field has been set.
func (o *AccountTransaction) HasUltimateCreditor() bool {
	if o != nil && o.UltimateCreditor != nil {
		return true
	}

	return false
}

// SetUltimateCreditor gets a reference to the given string and assigns it to the UltimateCreditor field.
func (o *AccountTransaction) SetUltimateCreditor(v string) {
	o.UltimateCreditor = &v
}

// GetUltimateDebtor returns the UltimateDebtor field value if set, zero value otherwise.
func (o *AccountTransaction) GetUltimateDebtor() string {
	if o == nil || o.UltimateDebtor == nil {
		var ret string
		return ret
	}
	return *o.UltimateDebtor
}

// GetUltimateDebtorOk returns a tuple with the UltimateDebtor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransaction) GetUltimateDebtorOk() (*string, bool) {
	if o == nil || o.UltimateDebtor == nil {
		return nil, false
	}
	return o.UltimateDebtor, true
}

// HasUltimateDebtor returns a boolean if a field has been set.
func (o *AccountTransaction) HasUltimateDebtor() bool {
	if o != nil && o.UltimateDebtor != nil {
		return true
	}

	return false
}

// SetUltimateDebtor gets a reference to the given string and assigns it to the UltimateDebtor field.
func (o *AccountTransaction) SetUltimateDebtor(v string) {
	o.UltimateDebtor = &v
}

func (o AccountTransaction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TransactionId != nil {
		toSerialize["transactionId"] = o.TransactionId
	}
	if o.EntryReference != nil {
		toSerialize["entryReference"] = o.EntryReference
	}
	if o.CheckId != nil {
		toSerialize["checkId"] = o.CheckId
	}
	if o.CreditorId != nil {
		toSerialize["creditorId"] = o.CreditorId
	}
	if o.CreditorName != nil {
		toSerialize["creditorName"] = o.CreditorName
	}
	if o.CreditorAccount != nil {
		toSerialize["creditorAccount"] = o.CreditorAccount
	}
	if o.DebtorName != nil {
		toSerialize["debtorName"] = o.DebtorName
	}
	if o.DebtorAccount != nil {
		toSerialize["debtorAccount"] = o.DebtorAccount
	}
	if o.TransactionAmount != nil {
		toSerialize["transactionAmount"] = o.TransactionAmount
	}
	if o.BankTransactionCode != nil {
		toSerialize["bankTransactionCode"] = o.BankTransactionCode
	}
	if o.BookingDate != nil {
		toSerialize["bookingDate"] = o.BookingDate
	}
	if o.ValueDate != nil {
		toSerialize["valueDate"] = o.ValueDate
	}
	if o.MandateId != nil {
		toSerialize["mandateId"] = o.MandateId
	}
	if o.PurposeCode != nil {
		toSerialize["purposeCode"] = o.PurposeCode
	}
	if o.RemittanceInformationUnstructured != nil {
		toSerialize["remittanceInformationUnstructured"] = o.RemittanceInformationUnstructured
	}
	if o.AdditionalInformation != nil {
		toSerialize["additionalInformation"] = o.AdditionalInformation
	}
	if o.ProprietaryBankTransactionCode != nil {
		toSerialize["proprietaryBankTransactionCode"] = o.ProprietaryBankTransactionCode
	}
	if o.UltimateCreditor != nil {
		toSerialize["ultimateCreditor"] = o.UltimateCreditor
	}
	if o.UltimateDebtor != nil {
		toSerialize["ultimateDebtor"] = o.UltimateDebtor
	}
	return json.Marshal(toSerialize)
}

type NullableAccountTransaction struct {
	value *AccountTransaction
	isSet bool
}

func (v NullableAccountTransaction) Get() *AccountTransaction {
	return v.value
}

func (v *NullableAccountTransaction) Set(val *AccountTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountTransaction(val *AccountTransaction) *NullableAccountTransaction {
	return &NullableAccountTransaction{value: val, isSet: true}
}

func (v NullableAccountTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


