/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// RequisitionLinkParamsRequest RequisitionLinkParamsSerializer.
type RequisitionLinkParamsRequest struct {
	// ASPSP ID. Should match one used while creating EUA, if it's linked to this requisition
	AspspId string `json:"aspsp_id"`
}

// NewRequisitionLinkParamsRequest instantiates a new RequisitionLinkParamsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequisitionLinkParamsRequest(aspspId string) *RequisitionLinkParamsRequest {
	this := RequisitionLinkParamsRequest{}
	this.AspspId = aspspId
	return &this
}

// NewRequisitionLinkParamsRequestWithDefaults instantiates a new RequisitionLinkParamsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequisitionLinkParamsRequestWithDefaults() *RequisitionLinkParamsRequest {
	this := RequisitionLinkParamsRequest{}
	return &this
}

// GetAspspId returns the AspspId field value
func (o *RequisitionLinkParamsRequest) GetAspspId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AspspId
}

// GetAspspIdOk returns a tuple with the AspspId field value
// and a boolean to check if the value has been set.
func (o *RequisitionLinkParamsRequest) GetAspspIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AspspId, true
}

// SetAspspId sets field value
func (o *RequisitionLinkParamsRequest) SetAspspId(v string) {
	o.AspspId = v
}

func (o RequisitionLinkParamsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["aspsp_id"] = o.AspspId
	}
	return json.Marshal(toSerialize)
}

type NullableRequisitionLinkParamsRequest struct {
	value *RequisitionLinkParamsRequest
	isSet bool
}

func (v NullableRequisitionLinkParamsRequest) Get() *RequisitionLinkParamsRequest {
	return v.value
}

func (v *NullableRequisitionLinkParamsRequest) Set(val *RequisitionLinkParamsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequisitionLinkParamsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequisitionLinkParamsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequisitionLinkParamsRequest(val *RequisitionLinkParamsRequest) *NullableRequisitionLinkParamsRequest {
	return &NullableRequisitionLinkParamsRequest{value: val, isSet: true}
}

func (v NullableRequisitionLinkParamsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequisitionLinkParamsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


