/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"fmt"
)

// Status1c5EnumExpired the model 'Status1c5EnumExpired'
type Status1c5EnumExpired string

// List of Status1c5EnumExpired
const (
	STATUS1C5ENUMEXPIRED_EX Status1c5EnumExpired = "EX"
	STATUS1C5ENUMEXPIRED_EXPIRED Status1c5EnumExpired = "EXPIRED"
)

// All allowed values of Status1c5EnumExpired enum
var AllowedStatus1c5EnumExpiredEnumValues = []Status1c5EnumExpired{
	"EX",
	"EXPIRED",
}

func (v *Status1c5EnumExpired) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status1c5EnumExpired(value)
	for _, existing := range AllowedStatus1c5EnumExpiredEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status1c5EnumExpired", value)
}

// NewStatus1c5EnumExpiredFromValue returns a pointer to a valid Status1c5EnumExpired
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus1c5EnumExpiredFromValue(v string) (*Status1c5EnumExpired, error) {
	ev := Status1c5EnumExpired(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status1c5EnumExpired: valid values are %v", v, AllowedStatus1c5EnumExpiredEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status1c5EnumExpired) IsValid() bool {
	for _, existing := range AllowedStatus1c5EnumExpiredEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status1c5EnumExpired value
func (v Status1c5EnumExpired) Ptr() *Status1c5EnumExpired {
	return &v
}

type NullableStatus1c5EnumExpired struct {
	value *Status1c5EnumExpired
	isSet bool
}

func (v NullableStatus1c5EnumExpired) Get() *Status1c5EnumExpired {
	return v.value
}

func (v *NullableStatus1c5EnumExpired) Set(val *Status1c5EnumExpired) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumExpired) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumExpired) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumExpired(val *Status1c5EnumExpired) *NullableStatus1c5EnumExpired {
	return &NullableStatus1c5EnumExpired{value: val, isSet: true}
}

func (v NullableStatus1c5EnumExpired) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumExpired) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

