/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// RequisitionLinks RequisitionLinksSerializer.
type RequisitionLinks struct {
	Initiate *string `json:"initiate,omitempty"`
}

// NewRequisitionLinks instantiates a new RequisitionLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequisitionLinks() *RequisitionLinks {
	this := RequisitionLinks{}
	return &this
}

// NewRequisitionLinksWithDefaults instantiates a new RequisitionLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequisitionLinksWithDefaults() *RequisitionLinks {
	this := RequisitionLinks{}
	return &this
}

// GetInitiate returns the Initiate field value if set, zero value otherwise.
func (o *RequisitionLinks) GetInitiate() string {
	if o == nil || o.Initiate == nil {
		var ret string
		return ret
	}
	return *o.Initiate
}

// GetInitiateOk returns a tuple with the Initiate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequisitionLinks) GetInitiateOk() (*string, bool) {
	if o == nil || o.Initiate == nil {
		return nil, false
	}
	return o.Initiate, true
}

// HasInitiate returns a boolean if a field has been set.
func (o *RequisitionLinks) HasInitiate() bool {
	if o != nil && o.Initiate != nil {
		return true
	}

	return false
}

// SetInitiate gets a reference to the given string and assigns it to the Initiate field.
func (o *RequisitionLinks) SetInitiate(v string) {
	o.Initiate = &v
}

func (o RequisitionLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Initiate != nil {
		toSerialize["initiate"] = o.Initiate
	}
	return json.Marshal(toSerialize)
}

type NullableRequisitionLinks struct {
	value *RequisitionLinks
	isSet bool
}

func (v NullableRequisitionLinks) Get() *RequisitionLinks {
	return v.value
}

func (v *NullableRequisitionLinks) Set(val *RequisitionLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableRequisitionLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableRequisitionLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequisitionLinks(val *RequisitionLinks) *NullableRequisitionLinks {
	return &NullableRequisitionLinks{value: val, isSet: true}
}

func (v NullableRequisitionLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequisitionLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


