/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// AccountV2StatusEnumDiscovered struct for AccountV2StatusEnumDiscovered
type AccountV2StatusEnumDiscovered struct {
	DISCOVERED string `json:"DISCOVERED"`
}

// NewAccountV2StatusEnumDiscovered instantiates a new AccountV2StatusEnumDiscovered object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountV2StatusEnumDiscovered(dISCOVERED string) *AccountV2StatusEnumDiscovered {
	this := AccountV2StatusEnumDiscovered{}
	this.DISCOVERED = dISCOVERED
	return &this
}

// NewAccountV2StatusEnumDiscoveredWithDefaults instantiates a new AccountV2StatusEnumDiscovered object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountV2StatusEnumDiscoveredWithDefaults() *AccountV2StatusEnumDiscovered {
	this := AccountV2StatusEnumDiscovered{}
	return &this
}

// GetDISCOVERED returns the DISCOVERED field value
func (o *AccountV2StatusEnumDiscovered) GetDISCOVERED() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DISCOVERED
}

// GetDISCOVEREDOk returns a tuple with the DISCOVERED field value
// and a boolean to check if the value has been set.
func (o *AccountV2StatusEnumDiscovered) GetDISCOVEREDOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DISCOVERED, true
}

// SetDISCOVERED sets field value
func (o *AccountV2StatusEnumDiscovered) SetDISCOVERED(v string) {
	o.DISCOVERED = v
}

func (o AccountV2StatusEnumDiscovered) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["DISCOVERED"] = o.DISCOVERED
	}
	return json.Marshal(toSerialize)
}

type NullableAccountV2StatusEnumDiscovered struct {
	value *AccountV2StatusEnumDiscovered
	isSet bool
}

func (v NullableAccountV2StatusEnumDiscovered) Get() *AccountV2StatusEnumDiscovered {
	return v.value
}

func (v *NullableAccountV2StatusEnumDiscovered) Set(val *AccountV2StatusEnumDiscovered) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountV2StatusEnumDiscovered) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountV2StatusEnumDiscovered) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountV2StatusEnumDiscovered(val *AccountV2StatusEnumDiscovered) *NullableAccountV2StatusEnumDiscovered {
	return &NullableAccountV2StatusEnumDiscovered{value: val, isSet: true}
}

func (v NullableAccountV2StatusEnumDiscovered) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountV2StatusEnumDiscovered) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


