/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"fmt"
)

// Status1c5EnumRejected the model 'Status1c5EnumRejected'
type Status1c5EnumRejected string

// List of Status1c5EnumRejected
const (
	STATUS1C5ENUMREJECTED_RJ Status1c5EnumRejected = "RJ"
	STATUS1C5ENUMREJECTED_REJECTED Status1c5EnumRejected = "REJECTED"
)

// All allowed values of Status1c5EnumRejected enum
var AllowedStatus1c5EnumRejectedEnumValues = []Status1c5EnumRejected{
	"RJ",
	"REJECTED",
}

func (v *Status1c5EnumRejected) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status1c5EnumRejected(value)
	for _, existing := range AllowedStatus1c5EnumRejectedEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status1c5EnumRejected", value)
}

// NewStatus1c5EnumRejectedFromValue returns a pointer to a valid Status1c5EnumRejected
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus1c5EnumRejectedFromValue(v string) (*Status1c5EnumRejected, error) {
	ev := Status1c5EnumRejected(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status1c5EnumRejected: valid values are %v", v, AllowedStatus1c5EnumRejectedEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status1c5EnumRejected) IsValid() bool {
	for _, existing := range AllowedStatus1c5EnumRejectedEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status1c5EnumRejected value
func (v Status1c5EnumRejected) Ptr() *Status1c5EnumRejected {
	return &v
}

type NullableStatus1c5EnumRejected struct {
	value *Status1c5EnumRejected
	isSet bool
}

func (v NullableStatus1c5EnumRejected) Get() *Status1c5EnumRejected {
	return v.value
}

func (v *NullableStatus1c5EnumRejected) Set(val *Status1c5EnumRejected) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumRejected) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumRejected) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumRejected(val *Status1c5EnumRejected) *NullableStatus1c5EnumRejected {
	return &NullableStatus1c5EnumRejected{value: val, isSet: true}
}

func (v NullableStatus1c5EnumRejected) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumRejected) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

