/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// AccountV2StatusEnumReady struct for AccountV2StatusEnumReady
type AccountV2StatusEnumReady struct {
	READY string `json:"READY"`
}

// NewAccountV2StatusEnumReady instantiates a new AccountV2StatusEnumReady object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountV2StatusEnumReady(rEADY string) *AccountV2StatusEnumReady {
	this := AccountV2StatusEnumReady{}
	this.READY = rEADY
	return &this
}

// NewAccountV2StatusEnumReadyWithDefaults instantiates a new AccountV2StatusEnumReady object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountV2StatusEnumReadyWithDefaults() *AccountV2StatusEnumReady {
	this := AccountV2StatusEnumReady{}
	return &this
}

// GetREADY returns the READY field value
func (o *AccountV2StatusEnumReady) GetREADY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.READY
}

// GetREADYOk returns a tuple with the READY field value
// and a boolean to check if the value has been set.
func (o *AccountV2StatusEnumReady) GetREADYOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.READY, true
}

// SetREADY sets field value
func (o *AccountV2StatusEnumReady) SetREADY(v string) {
	o.READY = v
}

func (o AccountV2StatusEnumReady) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["READY"] = o.READY
	}
	return json.Marshal(toSerialize)
}

type NullableAccountV2StatusEnumReady struct {
	value *AccountV2StatusEnumReady
	isSet bool
}

func (v NullableAccountV2StatusEnumReady) Get() *AccountV2StatusEnumReady {
	return v.value
}

func (v *NullableAccountV2StatusEnumReady) Set(val *AccountV2StatusEnumReady) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountV2StatusEnumReady) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountV2StatusEnumReady) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountV2StatusEnumReady(val *AccountV2StatusEnumReady) *NullableAccountV2StatusEnumReady {
	return &NullableAccountV2StatusEnumReady{value: val, isSet: true}
}

func (v NullableAccountV2StatusEnumReady) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountV2StatusEnumReady) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


