/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// AccountTransactionDebtorAccount struct for AccountTransactionDebtorAccount
type AccountTransactionDebtorAccount struct {
	Iban *string `json:"iban,omitempty"`
}

// NewAccountTransactionDebtorAccount instantiates a new AccountTransactionDebtorAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountTransactionDebtorAccount() *AccountTransactionDebtorAccount {
	this := AccountTransactionDebtorAccount{}
	return &this
}

// NewAccountTransactionDebtorAccountWithDefaults instantiates a new AccountTransactionDebtorAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountTransactionDebtorAccountWithDefaults() *AccountTransactionDebtorAccount {
	this := AccountTransactionDebtorAccount{}
	return &this
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *AccountTransactionDebtorAccount) GetIban() string {
	if o == nil || o.Iban == nil {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransactionDebtorAccount) GetIbanOk() (*string, bool) {
	if o == nil || o.Iban == nil {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *AccountTransactionDebtorAccount) HasIban() bool {
	if o != nil && o.Iban != nil {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *AccountTransactionDebtorAccount) SetIban(v string) {
	o.Iban = &v
}

func (o AccountTransactionDebtorAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Iban != nil {
		toSerialize["iban"] = o.Iban
	}
	return json.Marshal(toSerialize)
}

type NullableAccountTransactionDebtorAccount struct {
	value *AccountTransactionDebtorAccount
	isSet bool
}

func (v NullableAccountTransactionDebtorAccount) Get() *AccountTransactionDebtorAccount {
	return v.value
}

func (v *NullableAccountTransactionDebtorAccount) Set(val *AccountTransactionDebtorAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountTransactionDebtorAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountTransactionDebtorAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountTransactionDebtorAccount(val *AccountTransactionDebtorAccount) *NullableAccountTransactionDebtorAccount {
	return &NullableAccountTransactionDebtorAccount{value: val, isSet: true}
}

func (v NullableAccountTransactionDebtorAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountTransactionDebtorAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


