/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"fmt"
)

// Status1c5EnumSelectingAccounts the model 'Status1c5EnumSelectingAccounts'
type Status1c5EnumSelectingAccounts string

// List of Status1c5EnumSelectingAccounts
const (
	STATUS1C5ENUMSELECTINGACCOUNTS_SA Status1c5EnumSelectingAccounts = "SA"
	STATUS1C5ENUMSELECTINGACCOUNTS_SELECTING_ACCOUNTS Status1c5EnumSelectingAccounts = "SELECTING_ACCOUNTS"
)

// All allowed values of Status1c5EnumSelectingAccounts enum
var AllowedStatus1c5EnumSelectingAccountsEnumValues = []Status1c5EnumSelectingAccounts{
	"SA",
	"SELECTING_ACCOUNTS",
}

func (v *Status1c5EnumSelectingAccounts) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status1c5EnumSelectingAccounts(value)
	for _, existing := range AllowedStatus1c5EnumSelectingAccountsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status1c5EnumSelectingAccounts", value)
}

// NewStatus1c5EnumSelectingAccountsFromValue returns a pointer to a valid Status1c5EnumSelectingAccounts
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus1c5EnumSelectingAccountsFromValue(v string) (*Status1c5EnumSelectingAccounts, error) {
	ev := Status1c5EnumSelectingAccounts(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status1c5EnumSelectingAccounts: valid values are %v", v, AllowedStatus1c5EnumSelectingAccountsEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status1c5EnumSelectingAccounts) IsValid() bool {
	for _, existing := range AllowedStatus1c5EnumSelectingAccountsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status1c5EnumSelectingAccounts value
func (v Status1c5EnumSelectingAccounts) Ptr() *Status1c5EnumSelectingAccounts {
	return &v
}

type NullableStatus1c5EnumSelectingAccounts struct {
	value *Status1c5EnumSelectingAccounts
	isSet bool
}

func (v NullableStatus1c5EnumSelectingAccounts) Get() *Status1c5EnumSelectingAccounts {
	return v.value
}

func (v *NullableStatus1c5EnumSelectingAccounts) Set(val *Status1c5EnumSelectingAccounts) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumSelectingAccounts) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumSelectingAccounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumSelectingAccounts(val *Status1c5EnumSelectingAccounts) *NullableStatus1c5EnumSelectingAccounts {
	return &NullableStatus1c5EnumSelectingAccounts{value: val, isSet: true}
}

func (v NullableStatus1c5EnumSelectingAccounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumSelectingAccounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

