/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// AccountTransactionCreditorAccount struct for AccountTransactionCreditorAccount
type AccountTransactionCreditorAccount struct {
	Iban *string `json:"iban,omitempty"`
	Bban *string `json:"bban,omitempty"`
}

// NewAccountTransactionCreditorAccount instantiates a new AccountTransactionCreditorAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountTransactionCreditorAccount() *AccountTransactionCreditorAccount {
	this := AccountTransactionCreditorAccount{}
	return &this
}

// NewAccountTransactionCreditorAccountWithDefaults instantiates a new AccountTransactionCreditorAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountTransactionCreditorAccountWithDefaults() *AccountTransactionCreditorAccount {
	this := AccountTransactionCreditorAccount{}
	return &this
}

// GetIban returns the Iban field value if set, zero value otherwise.
func (o *AccountTransactionCreditorAccount) GetIban() string {
	if o == nil || o.Iban == nil {
		var ret string
		return ret
	}
	return *o.Iban
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransactionCreditorAccount) GetIbanOk() (*string, bool) {
	if o == nil || o.Iban == nil {
		return nil, false
	}
	return o.Iban, true
}

// HasIban returns a boolean if a field has been set.
func (o *AccountTransactionCreditorAccount) HasIban() bool {
	if o != nil && o.Iban != nil {
		return true
	}

	return false
}

// SetIban gets a reference to the given string and assigns it to the Iban field.
func (o *AccountTransactionCreditorAccount) SetIban(v string) {
	o.Iban = &v
}

// GetBban returns the Bban field value if set, zero value otherwise.
func (o *AccountTransactionCreditorAccount) GetBban() string {
	if o == nil || o.Bban == nil {
		var ret string
		return ret
	}
	return *o.Bban
}

// GetBbanOk returns a tuple with the Bban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTransactionCreditorAccount) GetBbanOk() (*string, bool) {
	if o == nil || o.Bban == nil {
		return nil, false
	}
	return o.Bban, true
}

// HasBban returns a boolean if a field has been set.
func (o *AccountTransactionCreditorAccount) HasBban() bool {
	if o != nil && o.Bban != nil {
		return true
	}

	return false
}

// SetBban gets a reference to the given string and assigns it to the Bban field.
func (o *AccountTransactionCreditorAccount) SetBban(v string) {
	o.Bban = &v
}

func (o AccountTransactionCreditorAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Iban != nil {
		toSerialize["iban"] = o.Iban
	}
	if o.Bban != nil {
		toSerialize["bban"] = o.Bban
	}
	return json.Marshal(toSerialize)
}

type NullableAccountTransactionCreditorAccount struct {
	value *AccountTransactionCreditorAccount
	isSet bool
}

func (v NullableAccountTransactionCreditorAccount) Get() *AccountTransactionCreditorAccount {
	return v.value
}

func (v *NullableAccountTransactionCreditorAccount) Set(val *AccountTransactionCreditorAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountTransactionCreditorAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountTransactionCreditorAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountTransactionCreditorAccount(val *AccountTransactionCreditorAccount) *NullableAccountTransactionCreditorAccount {
	return &NullableAccountTransactionCreditorAccount{value: val, isSet: true}
}

func (v NullableAccountTransactionCreditorAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountTransactionCreditorAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


