/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// EnduserAcceptanceDetailsRequest Represents end-user details.
type EnduserAcceptanceDetailsRequest struct {
	UserAgent string `json:"user_agent"`
	IpAddress string `json:"ip_address"`
}

// NewEnduserAcceptanceDetailsRequest instantiates a new EnduserAcceptanceDetailsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnduserAcceptanceDetailsRequest(userAgent string, ipAddress string) *EnduserAcceptanceDetailsRequest {
	this := EnduserAcceptanceDetailsRequest{}
	this.UserAgent = userAgent
	this.IpAddress = ipAddress
	return &this
}

// NewEnduserAcceptanceDetailsRequestWithDefaults instantiates a new EnduserAcceptanceDetailsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnduserAcceptanceDetailsRequestWithDefaults() *EnduserAcceptanceDetailsRequest {
	this := EnduserAcceptanceDetailsRequest{}
	return &this
}

// GetUserAgent returns the UserAgent field value
func (o *EnduserAcceptanceDetailsRequest) GetUserAgent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value
// and a boolean to check if the value has been set.
func (o *EnduserAcceptanceDetailsRequest) GetUserAgentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserAgent, true
}

// SetUserAgent sets field value
func (o *EnduserAcceptanceDetailsRequest) SetUserAgent(v string) {
	o.UserAgent = v
}

// GetIpAddress returns the IpAddress field value
func (o *EnduserAcceptanceDetailsRequest) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *EnduserAcceptanceDetailsRequest) GetIpAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *EnduserAcceptanceDetailsRequest) SetIpAddress(v string) {
	o.IpAddress = v
}

func (o EnduserAcceptanceDetailsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user_agent"] = o.UserAgent
	}
	if true {
		toSerialize["ip_address"] = o.IpAddress
	}
	return json.Marshal(toSerialize)
}

type NullableEnduserAcceptanceDetailsRequest struct {
	value *EnduserAcceptanceDetailsRequest
	isSet bool
}

func (v NullableEnduserAcceptanceDetailsRequest) Get() *EnduserAcceptanceDetailsRequest {
	return v.value
}

func (v *NullableEnduserAcceptanceDetailsRequest) Set(val *EnduserAcceptanceDetailsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnduserAcceptanceDetailsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnduserAcceptanceDetailsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnduserAcceptanceDetailsRequest(val *EnduserAcceptanceDetailsRequest) *NullableEnduserAcceptanceDetailsRequest {
	return &NullableEnduserAcceptanceDetailsRequest{value: val, isSet: true}
}

func (v NullableEnduserAcceptanceDetailsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnduserAcceptanceDetailsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


