/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
	"fmt"
)

// Status1c5EnumGrantingAccess the model 'Status1c5EnumGrantingAccess'
type Status1c5EnumGrantingAccess string

// List of Status1c5EnumGrantingAccess
const (
	STATUS1C5ENUMGRANTINGACCESS_GA Status1c5EnumGrantingAccess = "GA"
	STATUS1C5ENUMGRANTINGACCESS_GRANTING_ACCESS Status1c5EnumGrantingAccess = "GRANTING_ACCESS"
)

// All allowed values of Status1c5EnumGrantingAccess enum
var AllowedStatus1c5EnumGrantingAccessEnumValues = []Status1c5EnumGrantingAccess{
	"GA",
	"GRANTING_ACCESS",
}

func (v *Status1c5EnumGrantingAccess) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Status1c5EnumGrantingAccess(value)
	for _, existing := range AllowedStatus1c5EnumGrantingAccessEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status1c5EnumGrantingAccess", value)
}

// NewStatus1c5EnumGrantingAccessFromValue returns a pointer to a valid Status1c5EnumGrantingAccess
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatus1c5EnumGrantingAccessFromValue(v string) (*Status1c5EnumGrantingAccess, error) {
	ev := Status1c5EnumGrantingAccess(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status1c5EnumGrantingAccess: valid values are %v", v, AllowedStatus1c5EnumGrantingAccessEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Status1c5EnumGrantingAccess) IsValid() bool {
	for _, existing := range AllowedStatus1c5EnumGrantingAccessEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Status1c5EnumGrantingAccess value
func (v Status1c5EnumGrantingAccess) Ptr() *Status1c5EnumGrantingAccess {
	return &v
}

type NullableStatus1c5EnumGrantingAccess struct {
	value *Status1c5EnumGrantingAccess
	isSet bool
}

func (v NullableStatus1c5EnumGrantingAccess) Get() *Status1c5EnumGrantingAccess {
	return v.value
}

func (v *NullableStatus1c5EnumGrantingAccess) Set(val *Status1c5EnumGrantingAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableStatus1c5EnumGrantingAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableStatus1c5EnumGrantingAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatus1c5EnumGrantingAccess(val *Status1c5EnumGrantingAccess) *NullableStatus1c5EnumGrantingAccess {
	return &NullableStatus1c5EnumGrantingAccess{value: val, isSet: true}
}

func (v NullableStatus1c5EnumGrantingAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatus1c5EnumGrantingAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

