/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// AccountDetailResponse struct for AccountDetailResponse
type AccountDetailResponse struct {
	Account *AccountDetail `json:"account,omitempty"`
}

// NewAccountDetailResponse instantiates a new AccountDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountDetailResponse() *AccountDetailResponse {
	this := AccountDetailResponse{}
	return &this
}

// NewAccountDetailResponseWithDefaults instantiates a new AccountDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountDetailResponseWithDefaults() *AccountDetailResponse {
	this := AccountDetailResponse{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *AccountDetailResponse) GetAccount() AccountDetail {
	if o == nil || o.Account == nil {
		var ret AccountDetail
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountDetailResponse) GetAccountOk() (*AccountDetail, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *AccountDetailResponse) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountDetail and assigns it to the Account field.
func (o *AccountDetailResponse) SetAccount(v AccountDetail) {
	o.Account = &v
}

func (o AccountDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableAccountDetailResponse struct {
	value *AccountDetailResponse
	isSet bool
}

func (v NullableAccountDetailResponse) Get() *AccountDetailResponse {
	return v.value
}

func (v *NullableAccountDetailResponse) Set(val *AccountDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountDetailResponse(val *AccountDetailResponse) *NullableAccountDetailResponse {
	return &NullableAccountDetailResponse{value: val, isSet: true}
}

func (v NullableAccountDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


