/*
Nordigen Account Information Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0 (v2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nordigen

import (
	"encoding/json"
)

// JWTObtainPairRequest Obtain JWT pair.
type JWTObtainPairRequest struct {
	// Secret id from /user-secrets/
	SecretId string `json:"secret_id"`
	// Secret key from /user-secrets/
	SecretKey string `json:"secret_key"`
}

// NewJWTObtainPairRequest instantiates a new JWTObtainPairRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJWTObtainPairRequest(secretId string, secretKey string) *JWTObtainPairRequest {
	this := JWTObtainPairRequest{}
	this.SecretId = secretId
	this.SecretKey = secretKey
	return &this
}

// NewJWTObtainPairRequestWithDefaults instantiates a new JWTObtainPairRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJWTObtainPairRequestWithDefaults() *JWTObtainPairRequest {
	this := JWTObtainPairRequest{}
	return &this
}

// GetSecretId returns the SecretId field value
func (o *JWTObtainPairRequest) GetSecretId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value
// and a boolean to check if the value has been set.
func (o *JWTObtainPairRequest) GetSecretIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecretId, true
}

// SetSecretId sets field value
func (o *JWTObtainPairRequest) SetSecretId(v string) {
	o.SecretId = v
}

// GetSecretKey returns the SecretKey field value
func (o *JWTObtainPairRequest) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *JWTObtainPairRequest) GetSecretKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *JWTObtainPairRequest) SetSecretKey(v string) {
	o.SecretKey = v
}

func (o JWTObtainPairRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["secret_id"] = o.SecretId
	}
	if true {
		toSerialize["secret_key"] = o.SecretKey
	}
	return json.Marshal(toSerialize)
}

type NullableJWTObtainPairRequest struct {
	value *JWTObtainPairRequest
	isSet bool
}

func (v NullableJWTObtainPairRequest) Get() *JWTObtainPairRequest {
	return v.value
}

func (v *NullableJWTObtainPairRequest) Set(val *JWTObtainPairRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJWTObtainPairRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJWTObtainPairRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJWTObtainPairRequest(val *JWTObtainPairRequest) *NullableJWTObtainPairRequest {
	return &NullableJWTObtainPairRequest{value: val, isSet: true}
}

func (v NullableJWTObtainPairRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJWTObtainPairRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


